schema_version: 1

context:
  name: youtube-to-anki
  version: 0.1.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/youtube-to-anki-${{ version }}.tar.gz
  sha256: 3491769992ca9f2dbce76b0105c47f153a57c84b4fa92d0dffe538abab212bdf

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - youtube-to-anki = youtube_to_anki.main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry-core >=1.0,<2.0
  run:
    - click >=7.1,<8.0
    - genanki >=0.10,<0.11
    - pydub >=0.25,<0.26
    - python >=${{ python_min }},<4.0
    - youtube-dl ==2021.04.07
    - youtube-transcript-api >=0.4.1,<0.5
    - ffmpeg >=4.3.1,<5.0

tests:
  - python:
      imports:
        - youtube_to_anki
        - youtube_to_anki.youtube
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - youtube-to-anki --help

about:
  summary: Convert YouTube videos to Anki decks.
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/youtube-to-anki/

extra:
  recipe-maintainers:
    - janjagusch
